name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
    paths:
      - 'flaskApi/**'  # 只有當 flaskApi 目錄有變更時才觸發
  workflow_dispatch:  # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: jellychang/hexaram-prediction
        tags: |
          type=raw,value=latest
          type=sha,format=short
    
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./flaskApi
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=jellychang/hexaram-prediction:buildcache
        cache-to: type=registry,ref=jellychang/hexaram-prediction:buildcache,mode=max
